export const majors = [
  "Accounting",
  "Accounting Technician",
  "Actuarial Science",
  "Aerospace/Aeronautical Engineering",
  "Agricultural Business & Management",
  "Agricultural Economics",
  "Agricultural Mechanization",
  "Agricultural Production",
  "Agricultural/Bioengineering",
  "American/English Literature",
  "Applied Mathematics",
  "Architectural Engineering",
  "Art History, Criticism & Conservation",
  "Art, General",
  "Arts, Technology, and Emerging Communication",
  "Astronomy",
  "Atmospheric Sciences & Meteorology",
  "Banking & Financial Support Services",
  "Biochemistry & Biophysics",
  "Biology, General",
  "Biomedical Engineering",
  "Business Administration & Management, General",
  "Business/Management Quantitative Methods, General",
  "Business/Managerial Economics",
  "Cell/Cellular Biology",
  "Chemical Engineering",
  "Chemistry",
  "Cinematography/Film/Vide Production",
  "Civil Engineering",
  "Computer & Information Sciences, General",
  "Computer Engineering",
  "Computer Information Systems",
  "Computer Networking/Telecommunications",
  "Computer Science",
  "Computer Software & Media Applications",
  "Computer System Administration",
  "Construction Engineering/Management",
  "Creative Writing",
  "Criminology",
  "Data Management Technology",
  "Data Science",
  "Dental Assisting",
  "Design & Visual Communications, General",
  "Ecology",
  "Economics",
  "Electrical Engineering",
  "Engineering (Pre-Engineering), General",
  "English Language & Literature, General",
  "Finance, General",
  "Financial Planning & Services",
  "Fine/Studio Arts",
  "Food Sciences & Technology",
  "Foreign Languages/Literatures, General",
  "French Language & Literature",
  "Genetics",
  "Geological & Earth Sciences",
  "Graphic Design",
  "Health Services Administration, General",
  "Human Resources Development/Training",
  "Human Resources Management",
  "Industrial Design",
  "Industrial Engineering",
  "Information Science",
  "Information Technology And Systems",
  "Insurance & Risk Management",
  "International Business Management",
  "International Relations & Affairs",
  "Investments & Securities",
  "Labor/Industrial Relations",
  "Law (Pre-Law)",
  "Legal Administrative Assisting/Secretarial",
  "Legal Studies, General",
  "Linguistics",
  "Logistics & Materials Management",
  "Management Information Systems",
  "Marine/Aquatic Biology",
  "Marketing Management & Research",
  "Mathematics, General",
  "Mechanical Engineering",
  "Medical Assisting",
  "Medical Office/Secretarial",
  "Medical Records",
  "Medical/Clinical Assisting, General",
  "Microbiology & Immunology",
  "Music, General",
  "Music, Theory & Composition",
  "Natural Resources Conservation, General",
  "Natural Resources Management",
  "Neuroscience",
  "Nuclear Engineering",
  "Occupational Therapy Assisting",
  "Philosophy",
  "Photography",
  "Physical Sciences, General",
  "Physical Therapy Assisting",
  "Physics",
  "Political Science & Government",
  "Psychology, Clinical & Counseling",
  "Psychology, General",
  "Public Speaking",
  "Sales, Merchandising, & Marketing, General",
  "Secretarial Studies & Office Administration",
  "Small Business Management/Operations",
  "Social Sciences, General",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Supply Chain Management",
  "Urban Studies/Urban Affairs",
  "Webpage Design",
] as [string, ...string[]];
